### ISSUE TITLE
New Function: file()

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-php#13]
## What
Add new method documentation file for a new PHP function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: example `file()`
Function description: Reads entire file into an array
File name: example `src/content/docs/06-file/08-fil-file.md`
The example is : `examples/06-file/08-fil-file.php`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute ` pint examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-php/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-php/blob/main/CONTRIBUTING.md

**Comment by roberto-butti** [comment]
I already created an example file using the `file()` function, especially using the context and remote files: https://github.com/roberto-butti/some-drops-of-php/blob/main/examples/06-file/08-fil-file.php

**Comment by Adtrex** [comment]
Hello, I would like to ask if there is anything to be done for this since you said you have created an example file

**Comment by roberto-butti** [comment]
Hi @Adtrex , thank you for asking. I wrote the example, but the missing thing is the documentation in the markdown file: `src/content/docs/06-file/08-fil-file.md`

**Comment by Adtrex** [comment]
Okay, Can I be assigned to this?
