### ISSUE TITLE
English content review

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-php#15]
If you see some mistake or some misspelling in one of markdown doc, please, smile and submit a PR ;)

I would like to suggest to open one PR per chapter.
Markdown files are in the `src/content/docs` directory in the `main` branch:
https://github.com/roberto-butti/some-drops-of-php/tree/main/src/content/docs

For other information, you can check the CONTRIBUTING.md file.
Thank you

**Comment by Ns-SheF** [comment]
Hi, hello. Can I have a go on this, please?

**Comment by roberto-butti** [comment]
> Hi, hello. Can I have a go on this, please?

of course @Ns-SheF , thank you!
please remember small and multiple PRs are better than one huge PR.

**Comment by aryankshl** [comment]
hey @roberto-butti can you please assign this to me?

**Comment by Angel-ifechukwu** [comment]
Hey @roberto-butti can you assign this to me?

**Comment by roberto-butti** [comment]
Assignment for the chapter reviews:

- [ ] Chapter 1, System, **not yet assigned**
- [x] Chapter 2, Array, assigned to @aryankshl 
- [x] Chapter 3, Vars, assigned to @Angel-ifechukwu 
- [ ] Chapter 4, Functions, **not yet assigned**
- [ ] Chapter 5, Strings, **not yet assigned**
- [x] Chapter 6, Files assigned to @Ns-SheF

**Comment by roberto-butti** [comment]
> hey @roberto-butti can you please assign this to me?

@aryankshl feel free to take one of the "not yet assigned" chapter https://github.com/roberto-butti/some-drops-of-php/issues/15#issuecomment-1760320461

**Comment by roberto-butti** [comment]
> Hey @roberto-butti can you assign this to me?

Hi @Angel-ifechukwu feel free to take one of the "not yet assigned" chapter https://github.com/roberto-butti/some-drops-of-php/issues/15#issuecomment-1760320461

**Comment by Ns-SheF** [comment]
Hi, @Angel-ifechukwu , @aryankshl , please do notify here on whichever chapter you take on so others might know which to pick.

**Comment by aryankshl** [comment]
I would like to work on chapter 2 Array

**Comment by Angel-ifechukwu** [comment]
I would like to work on Chapter 3 Vars

**Comment by roberto-butti** [comment]
Hi @Ns-SheF , @aryankshl , @Angel-ifechukwu  i updated the assignment : https://github.com/roberto-butti/some-drops-of-php/issues/15#issuecomment-1760320461

Thank you for contributing to "Some drops of PHP"
