### ISSUE TITLE
[bug] The website is down

### ISSUE THREAD

**Issue by ngdangtu-vn** [roberto-butti/some-drops-of-php#23]
It was running fine yesterday night (GTM+7) but I couldn't access it today. Here is screenshot of the problem:

![image](https://github.com/roberto-butti/some-drops-of-php/assets/68631458/1508533f-f438-45f8-8226-6068ffdd5169)

**Comment by roberto-butti** [comment]
Thank you for letting me know.
I will monitor the situation.
At the moment, it is a static artifact deployed on Vercel.
I will see if there is a more reliable option or hosting.
Thank you.

**Comment by ngdangtu-vn** [comment]
Does your use any server side code (or serverless)? If it is 100% static only, I would recommend Cloudflare Page. In the past, I used [surge.sh](https://surge.sh), it is a pretty good option as well if the project doesn't do much in Asia region...


If it requires server side, I would combine a static site hosting with Deno Deploy.
