### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by michaelthedev** [roberto-butti/some-drops-of-php#29]
Hello, I noticed some broken links on the readme

- The list of functions link
- The content link
![Screenshot_2023-12-25-08-52-08-014_com android chrome-edit](https://github.com/roberto-butti/some-drops-of-php/assets/39175160/a46abdd9-1338-4ca8-8e31-e6adc838877b)

**Comment by roberto-butti** [comment]
thank you @michaelthedev for the feedback.

**Comment by roberto-butti** [comment]
Thank you @michaelthedev , I closed this issue , I've just released the fixes
