### ISSUE TITLE
New Function: count_chars()

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-php#33]
## What
Add new method documentation file for a new PHP function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: example `count_chars()`
Function description: Counts the occurrences of each character in a string
File name: example `src/content/docs/05-string/17-str-count-chars.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute ` pint examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-php/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-php/blob/main/CONTRIBUTING.md

**Comment by shahzdvp** [comment]
can i work on this

**Comment by roberto-butti** [comment]
of course @shahzdvp ! thank you!

**Comment by roberto-butti** [comment]
closed by @shahzdvp  with #40 , thank you
