### ISSUE TITLE
Check Markdown formatting

### ISSUE THREAD

**Issue by szepeviktor** [roberto-butti/some-drops-of-php#43]
Markdown code can be kept in check with https://github.com/DavidAnson/markdownlint-cli2
It can be configured to your liking.

**Comment by szepeviktor** [comment]
e.g. backticks vs. tildes
https://github.com/roberto-butti/some-drops-of-php/blob/a6f984f0df48b478ccf55118843cf0cc39ff7551/src/content/docs/05-string/16-str-levensthein.md?plain=1#L26

**Comment by roberto-butti** [comment]
Introduced markdown lint.
This is an amazing tool. Thank you @szepeviktor  for the suggestion!

**Comment by szepeviktor** [comment]
You're welcome.
