### ISSUE TITLE
Checking links

### ISSUE THREAD

**Issue by szepeviktor** [roberto-butti/some-drops-of-php#44]
lychee can be used to discover broken links.

e.g. https://github.com/roberto-butti/some-drops-of-php/blob/a6f984f0df48b478ccf55118843cf0cc39ff7551/src/content/docs/05-string/17-str-count-chars.md?plain=1#L82

Please consider using it and live without broken links.

**Comment by roberto-butti** [comment]
Thank you for the suggestion, I didn't know about this tool. It looks great.
https://github.com/lycheeverse/lychee

**Comment by roberto-butti** [comment]
introduced it, for running via Makefile
