### ISSUE TITLE
File naming

### ISSUE THREAD

**Issue by szepeviktor** [roberto-butti/some-drops-of-php#45]
1. `src/content/docs/04-functions/02-fns-arrowfunction.md` could be renamed to `02-fns-arrow-function.md`
2. `src/content/docs/05-string/16-str-levensthein.md` has a typo

**Comment by roberto-butti** [comment]
Thank you for raising the issue @szepeviktor

**Comment by roberto-butti** [comment]
I'm going to close this issue, i renamed the two files.
Thank you for the feedback!

**Comment by szepeviktor** [comment]
Very glad to contribute.
